server:
  port: 8080
spring:
  datasource:
    username: ruhr_new
    password: RUHR@007mysql
    url: jdbc:mysql://192.168.0.41:3306/ruhr_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name:  com.mysql.cj.jdbc.Driver
  redis:
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
    host: 192.168.136.129 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 1000ms # 连接超时时间
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.hangz.spring. .entity

#整合mybatis 显示打印sql以及参数（最重要）
logging:
  level:
    com.hangz.spring.mybatis.mapper: debug