server:
  port: 8080
spring:
  datasource:
    username: ruhr
    password: RUHR@007mysql
    url: jdbc:mysql://192.168.0.104:3306/aaatest?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name:  com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.hangz.spring. .entity